; PlatformIO configuration for RaceBox Mini Interface/Controller on ESP32-S3-DEVKITC-1

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.psram = enabled
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D LGFX_USE_V1=1
lib_deps =
  h2zero/NimBLE-Arduino @ ^1.4.1
  lovyan03/LovyanGFX @ ^1.1.16
  mathertel/RotaryEncoder @ ^1.5.3




